services:
  code-server:
      build: .
      container_name: code-server
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Etc/UTC
        - SUDO_PASSWORD=${SUDO_PASSWORD}
        - PROXY_DOMAIN=code.msws.xyz
        - DEFAULT_WORKSPACE=/config/workspace
      volumes:
        - "project-data:/config"
        - "install-data:/home/abc/.local/share/code-server"
      restart: always
      networks:
        - cloudflared
networks:
  cloudflared:
    external: true

volumes:
  project-data:
  install-data:
