version: '3'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "9213:3000"
    environment:
      GF_FEATURE_TOGGLES_ENABLE: "publicDashboards"
      GF_SERVER_ROOT_URL: "https://stats.msws.xyz"
    restart: always
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monolith_default

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=365d'
    networks:
      - monolith_default

volumes:
    grafana-data:
    prometheus-data:

networks:
  monolith_default:
    external: true
