services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    networks:
      - cloudflared
      - maria_internal
    environment:
      PUID: 1000 #change PUID if needed
      PGID: 1000  #change PGID if needed
      TZ: "Europe/Berlin" #change Time Zone if needed
      NEXTCLOUD_ADMIN_USER: "admin"
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: "drive.msws.xyz drive.local.msws.xyz"
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_HOST: nextclouddb
    volumes:
      - nextcloud-data:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  mariadb:
    image: mariadb
    container_name: nextclouddb
    networks:
      - maria_internal
    environment:
      #- PUID=1000 #change PUID if needed
      #- PGID=100  #change PGID if needed
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}  #change password
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ=America/LosAngeles #Change Time Zone if needed
    volumes:
      - nextcloud-mariadb-config:/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:alpine
    restart: always

networks:
  cloudflared:
    external: true
  maria_internal:

volumes:
  nextcloud-data:
  nextcloud-mariadb-config:
