version: "3"
services:
  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    networks:
      - monolith_default
      - maria_internal
    ports:
      - "8001:443"
    environment:
      PUID: 1000 #change PUID if needed
      PGID: 1000  #change PGID if needed
      TZ: "Europe/Berlin" #change Time Zone if needed
      NEXTCLOUD_ADMIN_USER: "admin"
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: "cloud.msws.xyz drive.msws.xyz"
      TRUSTED_PROXIES: "swag"
      OVERWRITEHOST: "swag"
      OVERWRITEPROTOCOL: "https"
      OVERWRITECLIURL: "https://cloud.msws.xyz"
      OVERWRITEWEBROOT: "https://cloud.msws.xyz"
    volumes:
      - nextcloud-data:/config
      - nextcloud-data:/data
    depends_on:
      - mariadb
    restart: unless-stopped

  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: nextclouddb
    networks:
      - maria_internal
    environment:
      - PUID=1000 #change PUID if needed
      - PGID=100  #change PGID if needed
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}  #change password
      - TZ=Europe/Berlin #Change Time Zone if needed
    volumes:
      - /home/iboaz/appdata/nextclouddb:/config
    restart: unless-stopped

networks:
  monolith_default:
    external: true
  maria_internal:

volumes:
  nextcloud-data:
