version: '3'
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: always
    volumes:
      - uptime-kuma:/app/data
    networks:
      - cloudflared

networks:
  cloudflared:
    external: true

volumes:
  uptime-kuma:
