services:
    chhoto-url:
        image: sintan1729/chhoto-url:latest
        restart: always
        container_name: chhoto-url
        environment:
            - db_url=/data/urls.sqlite
            - site_url=https://msws.xyz/s
            - password=${password}
        volumes:
            - "${PWD}:/data/"
        networks:
            - cloudflared

networks:
    cloudflared:
        external: true
