services:
    chhoto-url:
        image: sintan1729/chhoto-url:latest
        restart: unless-stopped
        container_name: chhoto-url
        ports:
            - 4567:4567
        environment:
            # Change if you want to mount the database somewhere else
            # In this case, you can get rid of the db volume below
            # and instead do a mount manually by specifying the location
            - db_url=/data/urls.sqlite

            # Change it in case you want to set the website name
            # displayed in front of the shorturls, defaults to
            # the hostname you're accessing it from
            - site_url=https://msws.xyz/s

            - password=${password}
            
            # Pass the redirect method, if needed TEMPORARY and PERMANENT
            # are accepted values, defaults to PERMANENT
            # - redirect_method=TEMPORARY
        volumes:
            - /home/iboaz/chhoto:/data/
        networks:
            - monolith_default

networks:
    monolith_default:
        external: true
