services:
  immich-public-proxy:
    image: alangrainger/immich-public-proxy:latest
    container_name: immich-public-proxy
    restart: always
    environment:
      - PUBLIC_BASE_URL=https://img.msws.xyz
      - IMMICH_URL=http://immich_server:2283
    healthcheck:
      test: curl -s http://localhost:3000/share/healthcheck -o /dev/null || exit 1
      start_period: 10s
      timeout: 5s
    networks:
      - cloudflared
networks:
  cloudflared:
    external: true
