services:
  selfbot:
    image: ghcr.io/msws/selfbot-24:latest
    restart: always
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - OPENAI_TOKEN=${OPENAI_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - TZ=America/Los_Angeles
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
