services:
  chyrplite:
    # image: ghcr.io/msws/docker-chyrp-lite:latest
    image: docker.io/library/chryp-lite:test
    container_name: chyrp-lite-default
    restart: always
    volumes:
      - data:/data
      - html:/var/www/html
    networks:
      - cloudflared
      - chyrp_internal
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - chyrp_internal
    #    ports:
    #      - "3306:3306"


volumes:
  data:
  html:
  dbdata:
networks:
  cloudflared:
    external: true
  chyrp_internal:
