version: "2"
services:
  swag:
    image: linuxserver/swag         #swag is the replacement for letsencrypt (see link below)
    container_name: swag
    cap_add:
      - NET_ADMIN
    ports:
      - 443:443
    environment:
      - PUID=1000 #change PUID if needed
      - PGID=1000  #change PGID if needed
      - "TZ=Europe/Berlin" # change Time Zone if needed
      - "URL=msws.xyz" #insert your domain name - yourdomain.url
      - "SUBDOMAINS=wildcard"
      - "EXTRA_DOMAINS=*.code.msws.xyz"
      - "VALIDATION=dns"
      - "DNSPLUGIN=cloudflare"
      - "EMAIL=imodmaker@gmail.com" # define email; required to renew certificate
    volumes:
      - "${PWD}/config:/config"
    networks:
      - cloudflared
    restart: unless-stopped

networks:
  cloudflared:
    external: true
