services:
  wakapi:
    image: ghcr.io/muety/wakapi:latest
    container_name: wakapi
    restart: always
    environment:
      WAKAPI_PASSWORD_SALT: "${WAKAPI_PASSWORD_SALT}"
      WAKAPI_PORT: "3002"
      WAKAPI_PUBLIC_URL: "https://waka.msws.xyz"
      WAKAPI_DB_HOST: "wakapi-database-1"
      WAKAPI_DB_PORT: "3306"
      WAKAPI_DB_USER: "${MYSQL_USER}"
      WAKAPI_DB_PASSWORD: "${MYSQL_PASSWORD}"
      WAKAPI_DB_NAME: "${MYSQL_DATABASE}"
      WAKAPI_DB_TYPE: "mysql"
      WAKAPI_ALLOW_SIGNUP: "false"
      WAKAPI_DISABLE_FRONTPAGE: "true"
      WAKAPI_EXPOSE_METRICS: "true"
      WAKAPI_LEADERBOARD_ENABLED: "true"
      WAKAPI_LEADERBOARD_SCOPE: "month"
      WAKAPI_LISTEN_IPV6: "-"
      WAKAPI_MAIL_SMTP_HOST: "${WAKAPI_MAIL_SMTP_HOST}"
      WAKAPI_MAIL_SMTP_PORT: "${WAKAPI_MAIL_SMTP_PORT}"
      WAKAPI_MAIL_SMTP_USER: "${WAKAPI_MAIL_SMTP_USER}"
      WAKAPI_MAIL_SMTP_PASS: "${WAKAPI_MAIL_SMTP_PASS}"
      WAKAPI_MAIL_SENDER: "${WAKAPI_MAIL_SENDER}"
      WAKAPI_IMPORT_MAX_RATE: 0
    volumes:
      - wakapi-data:/data
    networks:
      - cloudflared
      - mariadb
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - wakapi-db:/var/lib/mysql
    networks:
      - mariadb

volumes:
  wakapi-data:
  wakapi-db:

networks:
  cloudflared:
    external: true
  mariadb:
