version: '3.8'

services:
  wakapi:
    image: ghcr.io/muety/wakapi:latest
    container_name: wakapi
    restart: always
    ports:
      - "3002:3002"
    environment:
      WAKAPI_PASSWORD_SALT: "${WAKAPI_PASSWORD_SALT}"
      WAKAPI_PORT: "3002"
      WAKAPI_PUBLIC_URL: "https://waka.msws.xyz"
      WAKAPI_DB_HOST: "nextclouddb"
      WAKAPI_DB_PORT: "3306"
      WAKAPI_DB_USER: "wakapi_user"
      WAKAPI_DB_PASSWORD: "your-password"
      WAKAPI_DB_NAME: "wakapi"
      WAKAPI_DB_TYPE: "mysql"
      WAKAPI_ALLOW_SIGNUP: "false"
      WAKAPI_DISABLE_FRONTPAGE: "true"
      WAKAPI_EXPOSE_METRICS: "true"
      WAKAPI_LEADERBOARD_ENABLED: "true"
      WAKAPI_LEADERBOARD_SCOPE: "month"
    volumes:
      - wakapi-data:/data
    networks:
      - monolith_default
      - nextcloud_maria_internal

volumes:
  wakapi-data:

networks:
  monolith_default:
    external: true
  nextcloud_maria_internal:
    external: true
