version: "3"
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    # ports:
    #   - "8081:8081"
    volumes:
      - /home/iboaz/navidrome/music/metube:/downloads
    networks:
      - cloudflared
    environment:
      - 'YTDL_OPTIONS={"ignore_no_formats_error": true, "no-abort-on-error": true}'

networks:
  cloudflared:
    external: true
