services:
  cloudflared-public:
    image: cloudflare/cloudflared:latest
    restart: always 
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN: "${PUBLIC_TUNNEL_TOKEN}"
    networks:
      - cloudflared
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
  cloudflared-internal:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN: "${PRIVATE_TUNNEL_TOKEN}"
    network_mode: "host"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

networks:
  cloudflared:
    name: cloudflared
